import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Result from "../components/Result";
import requests from "../utils/request";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>HULU 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Result results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const url = `https://api.themoviedb.org/3${
    requests[genre]?.url || requests.fetchTrending.url
  }`;

  const request = await fetch(url).then((res) => res.json());
  console.log(url);

  return {
    props: {
      results: request.results,
    },
  };
}
